[build]
  command = "ng build --configuration production"
  publish = "dist/nordic-studio/browser/browser"

# El resto de tu configuración (como los redirects) puede ir debajo
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200